### ISSUE TITLE
The file called "nlwiki_20170620_tok_small.txt" was not found in the Data folder

### ISSUE THREAD

**Issue by Ashinhuang** [nlptown/nlp-notebooks#8]
Dear sir,
 In the first section "An Introduction to Word Embeddings"
when run 'WIKI_FILE = os.path.join("../data", "nlwiki_20170620_tok_small.txt")'
not found "nlwiki_20170620_tok_small.txt" in the data folder

Thanks for your help!

**Comment by elemley** [comment]
I am having the same issue. I suppose I will try to generate a text file that will work...

**Comment by yvespeirsman** [comment]
Hi, I've completely revised the notebook on word embeddings and added a new dataset.
